### PR TITLE
Add "RFF" Segment

### PR DESCRIPTION
**Pull request by Jaimies**
Add support for parsing the "RFF" (Reference) segment

### CODE REVIEW

**Comment by Jaimies** [comment]
Btw, https://www.truugo.com/edifact/d96a/*name_of_segment*/ is a pretty useful resource, they have most segments documented.

**Comment by Chemaclass** [comment]
To fix the red build you can run `composer csfix` <- this will run the code style fixer and ensure everything is according to the standards of the project. You can make sure the CI will be green by running `composer test-all` locally.

**Comment by Jaimies** [comment]
Thx, I'll do that

**Comment by Jaimies** [comment]
PHP CS Fixer complains about my PHP version (mine is 8.1, but the maximum supported version is 8.0), and if I run it with `PHP_CS_FIXER_IGNORE_ENV` set, I get the following error: 

```
The rules contain unknown fixers: "types_spaces".  
```

**Comment by Jaimies** [comment]
It also suggests updating to PHPCSFixer v3, maybe that will help

**Comment by Jaimies** [comment]
Just found the reason, I forgot to run `composer install` after updating the local repo

**Comment by Chemaclass** [comment]
Right, try "composer install" first, to ensure you have the latest version of all dependencies. Because I updated them all before creating the new version.

**Comment by Jaimies** [comment]
Should be fine now

**Comment by Jaimies** [comment]
Scrutinizer still fails, but from what I gathered, it does that all the time (I checked other commits and it's the same there)

**Review by Chemaclass — APPROVED** [review]
Looks good. Thank you! 👍

**Pull request merged**
